# Generated by Django 4.0.1 on 2022-01-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='author',
            new_name='user',
        ),
    ]
